### ISSUE TITLE
The old suggested translations are not set as old

### ISSUE THREAD

**Issue by amieiro** [GlotPress/GlotPress-WP#1498] opened 2022-10-05 06:15 UTC
When a translator is suggesting some translations, she can suggest different translations for the same string:

![image](https://user-images.githubusercontent.com/1667814/193992710-9312d412-6a5b-4c91-81f2-2379ebf8ab89.png)

In this situation, the 3 translations, made by the same translator, are set as waiting, but I think:
- The first translation should be set as old when the second translation is made.
- The second translation should be set as old when the third translation is made.

Currently, if I accept the third string, I get:
- The first and the second one as old.
- The third one as current.

![image](https://user-images.githubusercontent.com/1667814/193993146-65d90662-ab64-425e-b233-579a36459b0e.png)

I propose to set as old the translations made by a user when this user adds a new suggestion for the same original.

**Comment by psmits1567** [comment] 2022-10-05 06:50
If a user adds more then one suggestion for the same original, only the last one should remain. However if the translator decides to alter it again into the first suggested string, that should be possible, and that one should be shown. Currently that is not possible, because it is set to rejected/old.

**Comment by amieiro** [comment] 2022-10-05 06:57
@psmits1567 currently, in GlotPress all suggested translations are in waiting status. I have made this test:
- Suggest `— %s 1`.
- Suggest `— %s 2`.
- Suggest `— %s 3`.
- Modify `— %s 1`, suggesting `— %s 1b`.
- Modify `— %s 2`, suggesting `— %s 2b`.

All translations are in waiting status. I think all translations should be in old status, except  `— %s 2b`, which should be in waiting status.

![image](https://user-images.githubusercontent.com/1667814/193999022-c8bc71c4-11dc-41ac-8735-5afdf38443e1.png)

**Comment by pedro-mendonca** [comment] 2022-10-05 06:57
Good point. Maybe on opening the editor for the old translation, the button "Suggest" make it the only one waiting, making all the others "old" again.

**Comment by psmits1567** [comment] 2022-10-05 07:04
Yes only one should get waiting status, the others shoul be set to old

**Comment by akirk** [comment] 2022-10-05 07:38
If they re-suggest a previously suggested (but turned old) translation then I suppose it should re-activate this old conversation to waiting? I think we already currently have a UI problem if a user suggests an existing translation (as in: nothing happens and things seem broken).

**Comment by amieiro** [comment] 2022-10-05 07:42
[Discussion](https://wordpress.slack.com/archives/C02RP50LK/p1664955005135739) in the Polyglots weekly meeting.

**Comment by pedro-mendonca** [comment] 2022-10-05 07:45
> I think we already currently have a UI problem if a user suggests an existing translation

@akirk the user is notified that there is already a translation. But in the specific case of it being an old suggestion from his own, might be turned toggled to Waiting without getting an error message.

**Comment by psmits1567** [comment] 2022-10-05 07:45
Undeed you get a warning "already exists" so you cannot activate it again

**Comment by amieiro** [comment] 2022-10-05 07:55
Currently, if a translation is in waiting status, and you try to send it another time, you get an error:

![image](https://user-images.githubusercontent.com/1667814/194009272-0d933667-1f6b-426d-b6a8-848a8f571643.png)

**Comment by pedro-mendonca** [comment] 2022-10-05 07:58
I suggest the error message is removed if the user is trying to suggest an old one, and set it to waiting (turning the others as old)

**Comment by amieiro** [comment] 2022-10-05 09:42
If we mark as old the suggestions from this user when she suggests a new translation, we will not have this problem. I would not mark the old one as waiting when the user suggests it another time; instead, I would add the new translation, so we would have the full history for this translation.

**Comment by fxbenard** [comment] 2022-10-05 10:55
Only the last suggestion should be in waiting state, all the previous one should be turned as old and if a user suggest the same translation then it's just a new suggestion overiding the waiting one

**Comment by ocean90** [comment] 2022-10-10 14:16
This is a duplicate of #889 and #878.

I'm not really a fan of auto-rejecting other suggestions as someone may just want to submit two alternatives since they are not sure which one is better. This is more about an UI issue as mentioned in #878 than anything else.

**Comment by psmits1567** [comment] 2022-10-10 14:23
Honestly I have never seen a translator suggest a translation twice. If I am correct, then his change causes the previous suggestion to get the "old" state. If the translator refreshes his screen then the untranslated line is gone, and can only be found within "waiting"

**Closed as completed** 2023-03-08 13:45 UTC
Labels: [Status] Duplicate
