### ISSUE TITLE
prepare_original() mangles HTML tags if glossary entry for & exists

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#869] opened 2018-01-28 16:49 UTC
Original report: https://meta.trac.wordpress.org/ticket/3344

Example: https://translate.wordpress.org/projects/wp-plugins/insert-headers-and-footers/dev/sv/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=693346&filters%5Btranslation_id%5D=53182480

Screenshots:
<img width="539" alt="" src="https://user-images.githubusercontent.com/617637/35484678-753f94fc-0453-11e8-9ed2-9f5592088c00.png">
<img width="459" alt="" src="https://user-images.githubusercontent.com/617637/35484663-43d1c458-0453-11e8-9e51-12b02a5bc38c.png">
<img width="551" alt="" src="https://user-images.githubusercontent.com/617637/35484662-43b94414-0453-11e8-8e96-6b997842a124.png">

The HTML:

```html
<p class="original">These scripts will be printed above the &lt;code<span class="glossary-word" data-translations="[{&quot;translation&quot;:&quot;och&quot;,&quot;pos&quot;:&quot;noun&quot;,&quot;comment&quot;:&quot;&quot;,&quot;locale_entry&quot;:&quot;&quot;}]">&</span>gt;&amp;lt;/body<span class="glossary-word" data-translations="[{&quot;translation&quot;:&quot;och&quot;,&quot;pos&quot;:&quot;noun&quot;,&quot;comment&quot;:&quot;&quot;,&quot;locale_entry&quot;:&quot;&quot;}]">&</span>amp;gt;&lt;/code<span class="glossary-word" data-translations="[{&quot;translation&quot;:&quot;och&quot;,&quot;pos&quot;:&quot;noun&quot;,&quot;comment&quot;:&quot;&quot;,&quot;locale_entry&quot;:&quot;&quot;}]">&</span>gt; tag.</p>
```

**Comment by jyourstone** [comment] 2018-03-22 07:33
Any progress on this?

If it can't get fixed in the near future I'll remove the glossary entry for "&" in the meantime.

**Comment by toolstack** [comment] 2018-03-22 15:57
No motion at this time, I'd remove the glossary term for now.

**Comment by toolstack** [comment] 2018-10-03 15:34
The mangling is caused because we escape the translation before processing the glossary entries.  The causes some of the html entities to get identified as a term instead of being left alone.

The obvious solution (of not escaping until after the glossary terms have been added) doesn't work as we would then escape the spans used for the glossary terms, breaking the popups.

The solution is to process the original a chunk at a time, I'll have a PR shortly to implement this.

**Comment by toolstack** [comment] 2018-10-03 17:48
The PR will now show the original as:

![andpersand](https://user-images.githubusercontent.com/9053749/46427803-4f619700-c710-11e8-8abd-d73092144755.png)

Note the ampersand near the end is correctly highlight without mangling the code tags.

And by correctly I mean that since the original contains html entities, and the `&` is a valid word break character (think of something like Proctor&Gamble) it will get highlighted as a glossary term (`body&gt` gets split in to two words "body" and "gt").

Note: I added a couple of extra glossary terms to my test install which is why; these, the and will are marked as terms as well in the screenshot.

**Closed as completed** 2018-10-15 20:22 UTC
Labels: [Type] Bug, [Status] In Progress
