### ISSUE TITLE
Better UI - Part 1 Breadcrumb

### ISSUE THREAD

**Issue by La-Geek** [GlotPress/GlotPress-WP#883] opened 2018-03-18 23:49 UTC
Especially new translators are confused about the navigation (in this case breadcrumb) in Glotpress. 

You start with
![breadcrumb_start](https://user-images.githubusercontent.com/1585416/37572434-43800f12-2b0b-11e8-8010-975187183bd5.jpg)
you click on **Development (trunk)**
and you expect to see
![breadcrumb_shouldbe](https://user-images.githubusercontent.com/1585416/37572517-84b6803c-2b0c-11e8-9c39-b672aebde85b.jpg)
instead you see this breadcrumb
![breadcrumb_instead](https://user-images.githubusercontent.com/1585416/37572457-991bb3cc-2b0b-11e8-9832-aeee13f4046e.jpg)

If you navigate back over this breadcrumb, you will get to a completely different page.

## **One step back:**
![one_step_back](https://user-images.githubusercontent.com/1585416/37572672-bb80b9f0-2b0e-11e8-8ea3-29ceae5d356a.jpg)

## **Two steps back:**
![two_steps_back](https://user-images.githubusercontent.com/1585416/37572675-ceb3f424-2b0e-11e8-85da-96ac74303ce4.jpg)

## **For comparison, the first page from where you started and which you won't easily find again.**
![startpage](https://user-images.githubusercontent.com/1585416/37572679-dbad008a-2b0e-11e8-900b-e0e77ee552d7.jpg)

**Comment by ocean90** [comment] 2018-03-19 12:22
Closing as invalid since this is caused by the custom templates on translate.w.org. There's already a ticket for that: https://meta.trac.wordpress.org/ticket/3021

**Closed as completed by ocean90** 2018-03-19 12:22 UTC
Labels: [Status] Invalid
