### ISSUE TITLE
If you are editing a change requested and press "enter" the record is set to "current"

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1544] opened 2022-12-16 12:14 UTC
If you are editing a comment for "change requested"  and press enter, the record is set to "current"
That is unwanted behavior, as you only want a new line within the text. Now you need to type at the last position to prevent saving

**Comment by amieiro** [comment] 2022-12-19 07:39
Hi, Peter:

I have tested it at translate.wordpress.org 

![image](https://user-images.githubusercontent.com/1667814/208371527-5f7ac8fd-2c26-4098-b1e0-e1983576940f.png)
 
And in a standalone GlotPress installation 

![image](https://user-images.githubusercontent.com/1667814/208371688-183d072c-1f92-44fc-bfa3-ffe2d2b9467f.png)

And I can't reproduce the situation. In both situations, I:
- Open the row.
- Add some text in the comment textarea, pressing the Enter key to get a new line. This key creates a new line, as expected.

Please, can you try this without any extension (GlotDict, WPGPTools,...)?
If you continue to have the problem, can you explain step by step how to reproduce it? Thank you.

**Comment by psmits1567** [comment] 2022-12-19 13:14
Made a minor test this morning, but could not reproduce it myself today. But it happened several times last week. So I need to pay more attention when it happens. So I propose to keep this one open, until I am sure it does not happen again

**Comment by psmits1567** [comment] 2023-03-01 08:46
This happens when you use the combination of Shift +Enter, it took me a while to recognise that

**Comment by amieiro** [comment] 2023-09-30 14:14
`Shift+Enter` is the hotkey to save a translation ([see the code here](https://github.com/GlotPress/GlotPress/blob/6ebd75f91c3c2de6c52609d9eab7967f1132b34a/assets/js/editor.js#L179)), so I close this issue.

**Closed as completed by amieiro** 2023-09-30 14:14 UTC
Labels: [Status] Invalid
