### ISSUE TITLE
PHP Errors (6 Deprecated)

### ISSUE THREAD

**Issue by fernandopro** [GlotPress/GlotPress-WP#1518] opened 2022-11-07 18:57 UTC
- Wordpress : 6.1
- PHP version : 8

**PHP Errors:**
Deprecated || Required parameter $meta_key follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:82
Deprecated | Required parameter $meta_value follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:0
Deprecated | Required parameter $type follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:0
Deprecated | Required parameter $meta_key follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:168
Deprecated | Required parameter $meta_value follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:168
Deprecated | Required parameter $type follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:168

**Comment by ocean90** [comment] 2022-11-07 19:00
Duplicate of #1446.

**Closed as not planned** 2022-11-07 19:00 UTC
Labels: [Status] Duplicate
