### ISSUE TITLE
Better UI - Part 2 Hint to locale translation rules instead to handbook

### ISSUE THREAD

**Issue by La-Geek** [GlotPress/GlotPress-WP#884] opened 2018-03-18 23:56 UTC
In Glotpress you see this hint:
![hinweis_englisch](https://user-images.githubusercontent.com/1585416/37572729-b4f4cb8e-2b0f-11e8-8fed-095712fad96b.jpg)

It would be absolutely helpful for the entire translation process if the local rules, glossaries and slack channel were linked. Something like this:
![hinweis](https://user-images.githubusercontent.com/1585416/37572750-fe1d92c8-2b0f-11e8-8ac8-6768c7071706.jpg)

The hint should be a translatable string. Only if it was not translated, or no local links exist, the reference to the English manual should be displayed.

Translators may find the glotpress, if they click on the plugins or theme page on "translate it into your language". In this case they don't know the existing local rules/glossaries and slack-channels.

**Comment by ocean90** [comment] 2018-03-19 12:18
The help hint is a custom extension on translate.w.org. I actually like the idea to re-use the banner for locale specific resources. We can use the same list as in the email for new editors.
Would be good to have a ticket for that on meta.trac. https://meta.trac.wordpress.org/newticket?component=Translate+Site+%26+Plugins&type=enhancement

Although it's invalid in the first place I'm closing it as a duplicate of #709.

**Closed as completed by ocean90** 2018-03-19 12:18 UTC
Labels: [Status] Duplicate

**Comment by La-Geek** [comment] 2018-03-22 13:23
> Would be good to have a ticket for that on meta.trac. 

https://meta.trac.wordpress.org/ticket/3522
