### ISSUE TITLE
Allowing a validator to suggest a translation 

### ISSUE THREAD

**Issue by amieiro** [GlotPress/GlotPress-WP#1502] opened 2022-10-07 11:47 UTC
Sometimes a validator wants to suggest a translation, not add it, so another validator can review it to improve or to give feedback.

GlotPress doesn't allow this:

![image](https://user-images.githubusercontent.com/1667814/194545116-7e9673b1-524d-4cc0-8236-9929f5a7c0e5.png)

The same happens at [translate.w.org](https://translate.wordpress.org/):

![image](https://user-images.githubusercontent.com/1667814/194545465-886b417f-9a37-4514-a48d-bc7a16e1f774.png)

But GlotPress allows to a validator to upload a translation file and to suggest the translations (waiting status):

![image](https://user-images.githubusercontent.com/1667814/194545608-96340fdb-0f79-416d-8918-9c66793d38b1.png)

The same happens at [translate.w.org](https://translate.wordpress.org/):

![image](https://user-images.githubusercontent.com/1667814/194546065-b2cefc2b-33be-4257-9740-481cd0aa4507.png)

I propose to add a new button to allow a validator to suggest the translations. Props @oandregal

**Comment by ocean90** [comment] 2022-10-10 14:23
Duplicate of #589.

**Closed as not planned by ocean90** 2022-10-10 14:23 UTC
Labels: [Status] Duplicate
