### ISSUE TITLE
new feature idea: share link for recent translations or search results

### ISSUE THREAD

**Issue by qdinar** [GlotPress/GlotPress-WP#995] opened 2019-03-23 11:49 UTC
i would like to translate next 15 strings, (there are 15 strings in page wordpress translations... ) and then, get a link for this page with 15 translations, to show it to some group of people in social networks. now, it is not possible, because:

- address bar link does not work, because after translation, same url show new untranslated strings.
- if to show translated strings, sorted by date, (maybe also filtered by user), it gives this set of translations, but as soon as new translations are added, it will show other result.

seems, adding one of "earlier than", "newer than" filter options would be enough, to make it possible to get such urls.

**Comment by tobifjellner** [comment] 2019-03-23 12:13
The number of translation segments shown in one page is a setting per user.
In translate.wordpress.org you can hover over your username in the upper corner and select "Translate Settings" and adjust this.
Your suggestion might still be useful, as some kind of dynamic offset value.

**Comment by qdinar** [comment] 2019-03-23 17:11
i do not understand your comment at this place : "some kind of dynamic offset value" . "earlier than" date is not dynamic, and not offset. how and what dynamic offset value can be used for this? and now i have an idea: probably you say about to add an url argument, that gives how much strings to show. that would be dynamic, and would give offset value of the end of the list of strings to show...

**Comment by toolstack** [comment] 2019-03-23 18:33
Another way to do this would be to filter based on your userid, then sort by date added.  It would be a transient view of course as when you translated more items it would put those on the top of the list.

It would be a significant amount of work to add a newer/older filter option, I'm wondering how often this would really be used?

**Comment by ocean90** [comment] 2022-03-23 08:21
Marking as a duplicate of #1022.

**Closed as completed by ocean90** 2022-03-23 08:21 UTC
Labels: [Status] Duplicate, [Type] Enhancement
