### ISSUE TITLE
Characters "→" and "↵" can't be entered correctly

### ISSUE THREAD

**Issue by naokomc** [GlotPress/GlotPress-WP#711] opened 2017-05-03 05:52 UTC
## Problem

When you enter the character "→", it goes missing in the input field.
It looks like this is because → is used to indicate tabs &mdash; when I export the translation, I saw `\t` in place of the character.

The same problem exists for "↵" (which is a less likely character to be used as a part of translation...)

## Screenshot

![translations___japanese___development__trunk____glotpress_ _wordpress](https://cloud.githubusercontent.com/assets/34067/25649367/cde442d8-300f-11e7-8f47-eff19eb05a72.png)

## Example

https://translate.wordpress.org/projects/wp-plugins/nothing-much/dev/ja/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3003345&filters%5Btranslation_id%5D=48943156 (click the "Details" link)

**Comment by ocean90** [comment] 2017-05-03 06:03
Duplicate of #648.

**Closed as completed by ocean90** 2017-05-03 06:03 UTC
Labels: [Status] Duplicate
