### ISSUE TITLE
Modify the header of the new wide GlotPress screen

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1575] opened 2023-02-22 14:08 UTC
Due to the wider GlotPress screen but not modifying the header title, texts are overflown. It would be nicer to have the Title aligned to the left, so it starts at the same position as the table below
![image](https://user-images.githubusercontent.com/28138634/220644351-c13e3784-c816-4833-a60e-cc1bd2bbe01c.png)
Before the change the line was big enough to hold links to the addons currently in use by translators.
Now it looks like below
![image](https://user-images.githubusercontent.com/28138634/220644836-b51d0a02-1766-4195-b71b-47ec636debff.png)

**Comment by amieiro** [comment] 2023-02-22 14:42
Hi, Peter:

I have tested the title position with different widths and they are fine. Make sure you don't have another element interfering with this design: a browser extension,...

I am going to close this issue, because it is related with translate.wordpress.org and not with the GlotPress plugin. 

1875 px width:

![image](https://user-images.githubusercontent.com/1667814/220654676-6dee74c1-1ef7-442c-a432-fcfe73967953.png)

1200 px width:

![image](https://user-images.githubusercontent.com/1667814/220655048-8b70f954-d2d0-4eb1-af7f-13bc86ce89b1.png)

800 px width:

![image](https://user-images.githubusercontent.com/1667814/220655334-318e8014-18df-48c3-af37-b6a2b7934d96.png)

**Closed as completed by amieiro** 2023-02-22 14:42 UTC

**Comment by psmits1567** [comment] 2023-02-22 16:12
Where can I report this? Because the problem is caused by the new layout. There are several addons that add a link into the header. If you activate all currently heavy used addons, then it goes wrong. To test add GlotDict, WPGPT, and WP Translation Filler, then the title gets overwritten.

**Comment by amieiro** [comment] 2023-02-22 16:38
Hi, Peter:

It is caused by GlotDict, so I recommend you to open an issue [here](https://github.com/Mte90/GlotDict/issues). I have tested it in Firefox. If I open an incognito browser (it doesn't load any extension), the title position is fine.

![image](https://user-images.githubusercontent.com/1667814/220694329-4ddf560d-668a-43fe-aebd-41e61bd65a2c.png)

If I open Fifefox in normal mode (with GlotDict loaded), you can see the problem with the title position.

![image](https://user-images.githubusercontent.com/1667814/220694590-bcfa905c-cd9e-4073-9b97-24e25899f93e.png)
