### ISSUE TITLE
Add a color mark in the white spaces at the begging and at the end of an original and a translation 

### ISSUE THREAD

**Issue by amieiro** [GlotPress/GlotPress-WP#1499] opened 2022-10-05 09:39 UTC
Sometimes, the original string has white spaces at the begging and/or at the end. It happens the same with the translation. This issue proposes to add some color mark to show to the translator that the original and/or the translation has some white spaces at the begging and/or at the end.

See this image from [Poedit](https://poedit.net/) (props @pedro-mendonca).

![image](https://user-images.githubusercontent.com/1667814/194030467-46f65b9d-2ab8-4b6e-8bdb-ef8107d446d8.png)

More context in the [discussion](https://wordpress.slack.com/archives/C02RP4R9F/p1664959057106449) in the GlotPress monthly meeting.

**Comment by Zodiac1978** [comment] 2022-10-05 18:16
Duplicate of #863

**Comment by pedro-mendonca** [comment] 2022-10-05 18:41
Thanks @Zodiac1978

**Closed as not planned** 2022-10-10 14:18 UTC
Labels: [Status] Duplicate

**Comment by amieiro** [comment] 2022-10-10 14:37
There is an [active PR](https://github.com/GlotPress/GlotPress/pull/1500) related with this issue.
