### ISSUE TITLE
Deprecated logs

### ISSUE THREAD

**Issue by pentatonicfunk** [GlotPress/GlotPress-WP#1547] opened 2022-12-21 12:25 UTC
php 8.1, gp 3.0.0
```
PHP Deprecated:  Optional parameter $object_id declared before required parameter $type is implicitly treated as a required parameter in ../wp-content/plugins/glotpress/gp-includes/meta.php on line 82
Deprecated: Optional parameter $object_id declared before required parameter $type is implicitly treated as a required parameter in ../wp-content/plugins/glotpress/gp-includes/meta.php on line 168
```

**Comment by ocean90** [comment] 2022-12-21 16:35
Duplicate of #1446.

**Closed as not planned by ocean90** 2022-12-21 16:35 UTC
Labels: [Status] Duplicate
