### ISSUE TITLE
Documentation on all the functions

### ISSUE THREAD

**Issue by Mte90** [GlotPress/GlotPress-WP#805] opened 2017-08-27 14:32 UTC
Looking at the code all the functions of glotpress doesn't have documentation and to contribute is not very easy to understand the code.

As example before understand the cool function `gp_post` I had to look all the code.

**Comment by toolstack** [comment] 2017-08-27 16:01
Duplicate of #585/#584.

**Closed as completed by toolstack** 2017-08-27 16:01 UTC
Labels: [Status] Duplicate, [Type] Enhancement
