### ISSUE TITLE
Problem in suggesting first word based on glossary

### ISSUE THREAD

**Issue by farhadsakhaei** [GlotPress/GlotPress-WP#857] opened 2017-12-04 10:01 UTC
Hi,

I created a glossary, But suggestions based on glossary doesn't work on first word of sentence
Because of first capital letter, if I put that word in first capital format in glossary, It works for suggestion
But we add all words in all lowercase letters
It is better to make all letters to lowercase and check for any suggestion

**Comment by toolstack** [comment] 2017-12-04 13:41
Duplicate of #703, glossary terms will be case insensitive in the next release of GP.

**Closed as completed by toolstack** 2017-12-04 13:41 UTC
Labels: [Status] Duplicate
